function xlabel_Iteration_formatter

  xlabel( ...
    'Iteration, {\color{white}\it t}',...
    'FontName', 'Times New Roman', ...
    'Fontsize', 8 ...
  );

  drawnow;
  a = get( get( gca, 'XLabel' ), 'Extent' );

  text( ...
    a(1) + a(3), ...
    a(2) + a(4) / 2.5, ...
    '$t$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'right',...
    'VerticalAlignment', 'middle', ...
    'FontSize', 8 ...
  );

end